Hw1
kravtsun/au-sd pull request #1
Opened 2017-03-03 02:04 UTC by kravtsun

2017-03-07 08:19 UTC, yurii-litvinov requested changes
В целом всё так, есть некоторые замечания по коду, которые я хотел бы, чтобы Вы поправили: всякие пробелы-табуляции, закомментированные куски кода, неймспейсы (я бы реализации команд, кстати, сделал отдельным неймспейсом, они явно выделяются) и т.д. Всё править не обязательно, потому что там много просто комментариев, а не замечаний. По архитектуре я бы сказал, что CLICommandParser действительно слишком умный (особенно метод parse_all_commands выделяется своей сложностью), я бы его поделил на лексер, парсер и т.д. Но это тоже можно не править, потому что как у Вас тоже ок. Вообще, вполне годное решение, мне нравится, поправьте стилевые вещи --- будет зачтено

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/README.md
> +open solution in MS Visual Studio (ver. >= 2015) an build project 'cli'
Если Qt, то Qt Creator как среда разработки очень даже ничего --- на мой вкус, приятнее Visual Studio для C++-ных проектов. И если компилировать под винду mingw, не надо будет так много условной компиляции.

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/README.md
> +Parsing user's input is made by *CLICommandParser* class. It turns our raw input stream into string lexems
Я бы не сказал, что CLICommandParser можно рассматривать как часть View --- в классическом MVC View отвечает за отображение данных пользователю. CLICommandParser лучше считать частью контроллера, поскольку он обрабатывает ввод и решает, что делать. Но тут вообще MVC не очень уместен на мой вкус, потому что тут нет особого пользовательского интерфейса, нотификаций из модели вью о том, что данные обновились и надо перерисоваться, даже данных как таковых особо нет. Это больше похоже на архитектурный стиль (и паттерн) "Интерпретатор".

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/cli.pro
> +    src/cli_pwd_command.cpp
Я обычно ставлю слеш даже после последнего элемента, потому что его очень легко потом забыть при ручной модификации файла и получить странные ошибки компиляции.

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/cli.pro
> +	include/cli_echo_command.h \
Везде пробелы, а тут табуляция

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/cli.pro
> +QMAKE_CXXFLAGS += -std=c++11
`CONFIG += c++11` и так должен ставить этот флаг, кажется.

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/cli_tester/cli_tester.pro
> +	cli_word_count_command.o\
Тут тоже перемешаны пробелы и табуляции, нехорошо

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_application.h
> +#define CLI_APPLICATION_H
Мне больше нравится `#pragma once`, но дело вкуса.

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_application.h
> +    CLIApplication();
А зачем, конструктор по умолчанию ведь не сгенерится, если есть какой-то другой.

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_cat_command_test.h
> +        if (vs.empty()) return "\n";
Лучше return писать на отдельной строке, а ещё лучше брать его в фигурные скобки --- так читабельнее и отлаживаться проще

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_cat_command_test.h
> +    static void writeLinesToFile(const std::string &filename, const std::vector<std::string> &lines)
Методы лучше разделять пустой строкой

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_command.h
> +    CLICommand(std::istream &is, std::ostream &os, const ParamsListType &params={});
В C++ нет единого стайлгайда, но "=" всё-таки обычно выделяется пробелами

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_command_parser.h
> +    CLICommandParser(const CLIEnvironment &env);
Я бы написал 
```cpp
explicit CLICommandParser(const CLIEnvironment &env);
```
Потому что по смыслу не хочется получить неявное преобразование типов от CLIEnvironment в CLICommandParser

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_command_parser.h
> +    CLICommandPipe parse_all_commands(std::istream &is_);
Именовать параметры паблик-методов с подчёркиваниями неудобно, они в хелпе и всплывающих подсказках будут так и показываться. Лучше как раз параметрам давать красивые имена, а полям --- какие получится.

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_command_parser_test.h
> +//            std::cout << i << std::endl;
Оставлять в master закомментированный код --- плохо, потому что непонятно, то ли он нужен (и тогда его лучше раскомментировать), то ли нет (и тогда его лучше удалить совсем, в истории-то он останется).

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_command_queue.h
> + * @brief The CLICommandQueue class - commands executioneer.
executor. executioneer --- это "палач" :)

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_command_queue_test.h
> +#ifndef CLI_COMMAND_QUEUE_TEST_H
Кстати, я бы хранил тесты отдельно от основного кода, чтобы они не загромождали папку с кодом, но дело вкуса.

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_echo_command_test.h
> +    void single_test(const CLICommand::ParamsListType &params, const std::string &shouldbe)
лучше shouldBe

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_environment.h
> +    CLIEnvironment(const VarListType &vars);
Тоже лучше пометить его как explicit

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_environment.h
> +     * @param value
Пустые тэги лучше вообще убрать

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_environment.h
> +    const VarListType &get_vars();
get_vars, кажется, мог бы быть const

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_environment_test.h
> +        CLIEnvironment env, env2;
Лучше по одному объявлению переменной на строку --- длиннее, но будет трудно не заметить объявление

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_exception.h
> +	const char *what() const override;
Табуляция внезапно

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_interactive_command.h
> + * Template pattern.
~~"Шаблонный шаблон"? :)~~

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_application.h
> +class CLIApplication
В больших проектах принято вообще всё раскладывать по неймспейсам --- заводится один корневой неймспейс для проекта и остальные, по необходимости. Глобальное пространство имён обычно резервируют под имена из библиотек, которые не следуют таким правилам (та же Qt, например; тогда как STL проявляет на удивление больше сознательности и использует пространство имён std).

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/include/cli_parser.h
> +    CLIParser(const std::string &s);
explicit?

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/src/cli_command_parser.cpp
> +//        }
Тоже, комментарии в основной ветке --- это плохо

2017-03-07 08:19 UTC, yurii-litvinov commented on cli/src/cli_environment.cpp
> +//    }
И тут, и ниже ещё недобитые комментарии есть

2017-03-07 10:06 UTC, kravtsun commented on cli/cli.pro
> +QMAKE_CXXFLAGS += -std=c++11
Не задумывался над этим, хотя бы потому, что уже давно прошли те времена, когда я писал -std=c++0x. А тестировать под старый gnu-компилятор времени уже нет, да и желания тоже. Т.е. CONFIG += c++11 может и старый флаг использовать, я к тому. 
Мое решение: исправлю, руководствуясь вашим предположением и [вопросом](http://stackoverflow.com/questions/27412373/qt-5-config-c11-vs-qmake-cxxflags-std-c11-whats-better). 
P.S. Вообще говоря, я предполагал, что вы скажете, что зависимость от qmake в данном проекте вообще не нужна: можно убрать pro файл и всю логику сборки убрать в make, который есть везде. А на какой IDE я всё писал - никому не должно быть интересно.

2017-03-07 10:50 UTC, kravtsun commented on cli/include/cli_application.h
> +    CLIApplication();
Тогда не понимаю смысл приема занесения конструктора по умолчанию под секцию private? Если мы скрыли дефолтный конструктор, то значит наш объект в любом случае будет конструироваться другим конструктором.

2017-03-07 10:58 UTC, kravtsun commented on cli/include/cli_cat_command_test.h
> +    static void writeLinesToFile(const std::string &filename, const std::vector<std::string> &lines)
Здесь упустил: вообще говоря, во всем проекте я старался разделять в один пробел. Беспокоит меня то, что анализирующий под два часа мой код codacy не смог указать на такие простейшие ошибки стиля.

2017-03-07 11:01 UTC, kravtsun commented on cli/include/cli_command_parser.h
> +    CLICommandParser(const CLIEnvironment &env);
Запустил cppcheck на эту вещь, получил чуть больше:
[cli/include/cli_environment.h:47]: (style) Class 'CLIEnvironment' has a constructor with 1 argument that is not explicit.
[cli/include/cli_exception.h:33]: (style) Class 'CLIExitException' has a constructor with 1 argument that is not explicit.
[cli/include/cli_exception.h:65]: (style) Class 'CLINotImlementedException' has a constructor with 1 argument that is not explicit.
[cli/include/cli_exception.h:92]: (style) Class 'CLIUnknownError' has a constructor with 1 argument that is not explicit.
[cli/include/cli_command_parser.h:25]: (style) Class 'CLICommandParser' has a constructor with 1 argument that is not explicit.
[cli/include/cli_command_queue.h:23]: (style) Class 'CLICommandQueue' has a constructor with 1 argument that is not explicit.
[cli/include/cli_parser.h:20]: (style) Class 'CLIParser' has a constructor with 1 argument that is not explicit.
С вашего позволения исправлю все.

2017-03-07 11:15 UTC, kravtsun commented on cli/include/cli_command_queue.h
> + * @brief The CLICommandQueue class - commands executioneer.
Видеоигры - зло:) исправлю.

2017-03-07 11:20 UTC, kravtsun commented on cli/include/cli_echo_command_test.h
> +    void single_test(const CLICommand::ParamsListType &params, const std::string &shouldbe)
Здесь не соглашусь с вариантом исправления: camel case в проекте использовался только для именования классов и в тестах (чтобы парсер cxxtest не удивлялся), могу исправить на should_be, пойдет?

2017-03-07 11:24 UTC, kravtsun commented on cli/include/cli_environment.h
> +     * @param value
Будет ли doxygen всегда генерировать пустое объяснение для параметра, если я опущу пустой тэг?

2017-03-07 11:45 UTC, kravtsun commented on cli/include/cli_application.h
> +#define CLI_APPLICATION_H
Везде перед гардами добавил #pragma once.

2017-03-07 12:21 UTC, kravtsun commented on cli/include/cli_application.h
> +class CLIApplication
Здесь я решил подойти к вопросу кардинально: весь код положил в namespace cli, удалил префиксы CLI у всех классов (кроме тех, что в тестовом коде).
префиксы "cli_" оставил у имен исходных файлов и у гардов.

2017-03-07 13:32 UTC, kravtsun commented on cli/README.md
> +open solution in MS Visual Studio (ver. >= 2015) an build project 'cli'
На мой взгляд, проще представить программиста на Windows, не имеющего Qt Creator, чем программиста без Visual Studio. ну и насчет 
> на мой вкус, приятнее Visual Studio для C++-ных проектов
я бы поспорил, хотя, как говорится, "на вкус и цвет..."

2017-03-07 13:35 UTC, kravtsun commented on cli/README.md
> +Parsing user's input is made by *CLICommandParser* class. It turns our raw input stream into string lexems
Для моего CLICommandParser я бы не сказал, что он
> решает, что делать

На мой взгляд он ничего не решает - ему приходит входной поток от пользователя, который он всего лишь переводит в массивы строк. Да, заменяет вхождения переменных окружения, но не более того.  
Интерфейс терминала - тоже интерфейс, IMHO. 
Насчет паттерна "Интерпретатор": посмотрю позже, пока не хочу портить README непонятыми мной терминами.

2017-03-13 11:26 UTC, yurii-litvinov commented on cli/include/cli_application.h
> +#define CLI_APPLICATION_H
Одновременно и то и то использовать, в общем-то, довольно бессмысленно. Так оно и не будет компилиться древними компиляторами, и содержит громоздкий синтаксис стражей включения.

2017-03-13 11:30 UTC, kravtsun commented on cli/include/cli_application.h
> +#define CLI_APPLICATION_H
Понял, исправил обратно.

2017-03-13 11:30 UTC, yurii-litvinov commented on cli/README.md
> +Parsing user's input is made by *CLICommandParser* class. It turns our raw input stream into string lexems
Интерфейс терминала в плане архитектуры разительно отличается от оконного интерфейса --- он не реактивный (хотя, REPL можно рассматривать как вырожденный случай цикла обработки событий). И ему не надо реагировать на события в модели, почему я и написал, что MVC тут не очень подходит. Но это, конечно, зависит от точки зрения.

2017-03-13 11:53 UTC, yurii-litvinov approved these changes

2017-03-13 11:56 UTC, yurii-litvinov commented on cli/cli.pro
> +QMAKE_CXXFLAGS += -std=c++11
Да нет, qmake вполне ок, make неудобно писать, сопровождать, и вообще он платформенно-зависимым получится. тогда уж CMake :)

2017-03-13 11:59 UTC, yurii-litvinov commented on cli/include/cli_application.h
> +    CLIApplication();
Конструктор по умолчанию прячут (прятали) в private в основном для того, чтобы класс вообще нельзя было инстанциировать (или инстанциировать извне, в зависимости от того, есть ли у него реализация). Сейчас для этого обычно пишут `= delete`. Если есть другой конструктор, то дефолтного просто нет, насколько я помню C++

2017-03-13 12:00 UTC, yurii-litvinov commented on cli/include/cli_command_parser.h
> +    CLICommandParser(const CLIEnvironment &env);
👍

2017-03-13 12:01 UTC, yurii-litvinov commented on cli/include/cli_echo_command_test.h
> +    void single_test(const CLICommand::ParamsListType &params, const std::string &shouldbe)
Полностью согласен

2017-03-13 12:03 UTC, yurii-litvinov commented on cli/include/cli_environment.h
> +     * @param value
Не помню и морально не готов проверять :)

2017-05-08 15:36 UTC, merged